// File: UserManager.java (Updated with SQL integration)
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import java.awt.*;
import java.util.List;

public class UserManager {
    private JFrame window;
    private DefaultTableModel tableModel;
    private JTable userTable;
    private JTextField nameField, emailField, skillField;
    private JComboBox<String> typeCombo, levelCombo;
    
    // --- DATABASE INTEGRATION ---
    private DatabaseManager dbManager; // <-- CHANGED: Replaced ArrayList and nextUserId

    // --- Modern UI Color Palette ---
    private final Color bgColor = new Color(45, 52, 54);
    private final Color panelColor = new Color(53, 63, 64, 200);
    private final Color textColor = new Color(223, 230, 233);
    private final Color inputBgColor = new Color(99, 110, 114);
    private final Color accentColor = new Color(52, 152, 219);
    private final Color successColor = new Color(46, 204, 113);
    private final Color warningColor = new Color(230, 126, 34);
    private final Color dangerColor = new Color(231, 76, 60);

    public UserManager() {
        dbManager = new DatabaseManager(); // <-- CHANGED: Initialize the DatabaseManager
        
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) { /* Fallback */ }
        
        setupWindow();
        refreshUserTable(); // <-- CHANGED: Load initial data from the database
    }

    private void setupWindow() {
        window = new JFrame("User Management System");
        window.setSize(950, 700);
        window.setLocationRelativeTo(null);
        window.setLayout(new BorderLayout(10, 10));
        window.getContentPane().setBackground(bgColor);

        JPanel inputPanel = createInputPanel();
        JScrollPane scrollPane = createTablePanel();
        JPanel buttonPanel = createButtonPanel();

        window.add(inputPanel, BorderLayout.NORTH);
        window.add(scrollPane, BorderLayout.CENTER);
        window.add(buttonPanel, BorderLayout.SOUTH);
    }
    
    // --- NEW METHOD ---
    // This helper method reloads all user data from the database into the JTable.
    private void refreshUserTable() {
        tableModel.setRowCount(0); // Clear the existing table data
        List<String[]> users = dbManager.getAllUsers(); // Get all users from the database
        for (String[] user : users) {
            tableModel.addRow(user); // Add each user to the table model
        }
    }

    private void addUser() {
        String name = nameField.getText().trim();
        String email = emailField.getText().trim();
        String skill = skillField.getText().trim();

        if (name.isEmpty() || email.isEmpty() || (skillField.isEnabled() && skill.isEmpty())) {
            JOptionPane.showMessageDialog(window, "Please fill all required fields!", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(window, "Please enter a valid email address!", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- DATABASE LOGIC ---
        String[] userData = new String[] {
            null, // ID is auto-generated by the database
            name,
            email,
            (String) typeCombo.getSelectedItem(),
            skillField.isEnabled() ? skill : "N/A",
            levelCombo.isEnabled() ? (String) levelCombo.getSelectedItem() : "N/A",
            "Pending"
        };
        
        if (dbManager.addUser(userData)) {
            refreshUserTable(); // <-- CHANGED: Refresh the table from the DB
            clearFields();
            JOptionPane.showMessageDialog(window, "User registered successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(window, "Failed to add user. Email may already exist.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void verifyUser() {
        int selectedRow = userTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(window, "Please select a user to verify!", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // --- DATABASE LOGIC ---
        int userId = Integer.parseInt((String) tableModel.getValueAt(selectedRow, 0));
        String userName = (String) tableModel.getValueAt(selectedRow, 1);
        
        dbManager.updateUserStatus(userId); // <-- CHANGED: Update the user in the DB
        refreshUserTable(); // <-- CHANGED: Refresh the table to show the change
        
        JOptionPane.showMessageDialog(window, "User '" + userName + "' has been verified!", "Verification Complete", JOptionPane.INFORMATION_MESSAGE);
    }

    private void removeUser() {
        int selectedRow = userTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(window, "Please select a user to remove!", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // --- DATABASE LOGIC ---
        int userId = Integer.parseInt((String) tableModel.getValueAt(selectedRow, 0));
        String userName = (String) tableModel.getValueAt(selectedRow, 1);

        int choice = JOptionPane.showConfirmDialog(window,
            "Are you sure you want to permanently remove user '" + userName + "'?", "Confirm Deletion",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (choice == JOptionPane.YES_OPTION) {
            dbManager.deleteUser(userId); // <-- CHANGED: Delete the user from the DB
            refreshUserTable(); // <-- CHANGED: Refresh the table
            JOptionPane.showMessageDialog(window, "User '" + userName + "' has been removed.", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void clearFields() {
        nameField.setText("");
        emailField.setText("");
        skillField.setText("");
        typeCombo.setSelectedIndex(0);
        levelCombo.setSelectedIndex(0);
    }
    
    // The loadSampleData method is no longer needed as data is persistent.
    // If you want to add initial data, you could add it in the DatabaseManager constructor.
    
    public void showWindow() {
        window.setVisible(true);
    }

    // --- Unchanged UI Methods ---
    // (The rest of the UI code like createInputPanel, createTablePanel, styleTable, etc., remains the same)
    private JPanel createInputPanel() {
        JPanel inputPanel = new JPanel(new GridBagLayout());
        inputPanel.setOpaque(false);
        inputPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createTitledBorder(
                        BorderFactory.createLineBorder(accentColor, 1), " Register New User ",
                        javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                        javax.swing.border.TitledBorder.DEFAULT_POSITION,
                        new Font("Segoe UI", Font.BOLD, 14), textColor),
                BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(8, 8, 8, 8);
        gbc.anchor = GridBagConstraints.WEST;

        nameField = createStyledTextField(20);
        emailField = createStyledTextField(20);
        skillField = createStyledTextField(20);
        typeCombo = createStyledComboBox(new String[]{"Freelancer", "Client"});
        levelCombo = createStyledComboBox(new String[]{"Beginner", "Intermediate", "Advanced", "Expert"});

        typeCombo.addActionListener(e -> {
            boolean isFreelancer = "Freelancer".equals(typeCombo.getSelectedItem());
            skillField.setEnabled(isFreelancer);
            levelCombo.setEnabled(isFreelancer);
            if (!isFreelancer) { skillField.setText("N/A"); } else { skillField.setText(""); }
        });

        gbc.gridx = 0; gbc.gridy = 0; inputPanel.add(createStyledLabel("Name:"), gbc);
        gbc.gridx = 1; inputPanel.add(nameField, gbc);
        gbc.gridx = 2; inputPanel.add(createStyledLabel("Email:"), gbc);
        gbc.gridx = 3; inputPanel.add(emailField, gbc);
        gbc.gridx = 0; gbc.gridy = 1; inputPanel.add(createStyledLabel("Type:"), gbc);
        gbc.gridx = 1; inputPanel.add(typeCombo, gbc);
        gbc.gridx = 2; inputPanel.add(createStyledLabel("Skill:"), gbc);
        gbc.gridx = 3; inputPanel.add(skillField, gbc);
        gbc.gridx = 0; gbc.gridy = 2; inputPanel.add(createStyledLabel("Level:"), gbc);
        gbc.gridx = 1; inputPanel.add(levelCombo, gbc);
        return inputPanel;
    }
    private JScrollPane createTablePanel() {
        String[] columns = {"ID", "Name", "Email", "Type", "Skill", "Level", "Status"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        userTable = new JTable(tableModel);
        styleTable(userTable);
        JScrollPane scrollPane = new JScrollPane(userTable);
        scrollPane.getViewport().setBackground(bgColor);
        scrollPane.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
        return scrollPane;
    }
    private JPanel createButtonPanel() {
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 15, 10));
        buttonPanel.setOpaque(false);
        JButton addBtn = createStyledButton("✓  Add User", successColor);
        JButton verifyBtn = createStyledButton("✨ Verify Selected", accentColor);
        JButton removeBtn = createStyledButton("🗑️ Remove Selected", dangerColor);
        JButton clearBtn = createStyledButton("✗ Clear Fields", warningColor);
        addBtn.addActionListener(e -> addUser());
        verifyBtn.addActionListener(e -> verifyUser());
        removeBtn.addActionListener(e -> removeUser());
        clearBtn.addActionListener(e -> clearFields());
        buttonPanel.add(addBtn);
        buttonPanel.add(verifyBtn);
        buttonPanel.add(removeBtn);
        buttonPanel.add(clearBtn);
        return buttonPanel;
    }
    private void styleTable(JTable table) {
        table.setBackground(bgColor);
        table.setForeground(textColor);
        table.setGridColor(inputBgColor);
        table.setRowHeight(30);
        table.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        table.setSelectionBackground(accentColor);
        table.setSelectionForeground(Color.WHITE);
        JTableHeader header = table.getTableHeader();
        header.setBackground(new Color(25, 42, 86));
        header.setForeground(Color.WHITE);
        header.setFont(new Font("Segoe UI", Font.BOLD, 15));
        header.setBorder(BorderFactory.createLineBorder(accentColor));
        table.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int col) {
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);
                c.setBackground(row % 2 == 0 ? bgColor : new Color(55, 63, 66));
                if (col == 6) { // Status column
                    String status = (String) value;
                    if ("Verified".equals(status)) { c.setForeground(successColor); setFont(getFont().deriveFont(Font.BOLD));
                    } else if ("Pending".equals(status)) { c.setForeground(warningColor); setFont(getFont().deriveFont(Font.ITALIC)); }
                } else { c.setForeground(isSelected ? Color.WHITE : textColor); setFont(getFont().deriveFont(Font.PLAIN)); }
                setHorizontalAlignment(JLabel.CENTER);
                return c;
            }
        });
    }
    private JLabel createStyledLabel(String text) {
        JLabel label = new JLabel(text);
        label.setForeground(textColor);
        label.setFont(new Font("Segoe UI", Font.BOLD, 14));
        return label;
    }
    private JTextField createStyledTextField(int columns) {
        JTextField tf = new JTextField(columns);
        tf.setBackground(inputBgColor);
        tf.setForeground(textColor);
        tf.setCaretColor(accentColor);
        tf.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        tf.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(80, 80, 80)), BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        return tf;
    }
    private JComboBox<String> createStyledComboBox(String[] items) {
        JComboBox<String> cb = new JComboBox<>(items);
        cb.setBackground(inputBgColor);
        cb.setForeground(textColor);
        cb.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        return cb;
    }
    private JButton createStyledButton(String text, Color color) {
        JButton button = new JButton(text);
        button.setFont(new Font("Segoe UI", Font.BOLD, 14));
        button.setBackground(color);
        button.setForeground(Color.WHITE);
        button.setFocusPainted(false);
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        button.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        return button;
    }
}